DEFINES		:= -DARM9

SOURCEDIRS	:= src/arm9 \
							 external/PPX \
							 external/libadx-nds/arm9/source/adx \

INCLUDEDIRS	:= src/arm9 \
							 external/PPX \
							 external/libadx-nds/common \

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile.arm9