# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

DEFINES		:= -DARM9

SOURCEDIRS	:= src/arm9 \
							 external/NasiBentoDS/bento \
							 external/libadx-nds/arm9/source/adx

INCLUDEDIRS	:= src/arm9 \
							 external/NasiBentoDS/bento \
							 external/libadx-nds/common

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile.arm9