name: Build with BlocksDS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: skylyrac/blocksds:slim-v1.10.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run make
        run: make

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: darnell
          path: '*.nds'
